name: Setup test script
description: 'Setup test script, should be called after checkout'
inputs:
  cache:
    default: ""
    description: 'Cache key for test'
  report:
    default: "false"
    required: false
    description: 'Report results'
  script:
    required: true
    description: 'Script to run'
  coverage:
    default: "false"
    required: false
    description: "Collect coverage"
  setup-python:
    default: "true"
    required: false
    description: "Setup Python"
runs:
  using: 'composite'
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry

    - name: Setup Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.12'
        check-latest: true
        cache: poetry

    - name: Add python dependencies
      if: ${{ inputs.setup-python == 'true' }}
      shell: bash
      working-directory: ./scripts
      run: |
        poetry install

    - name: Install Go tools
      shell: bash
      if: ${{ inputs.coverage == 'true' }}
      run: |
        go install github.com/ZxillyFork/courtney@9f98af51b9fb040946fa7c035cd5a641c5e524f2

    - name: Cache test binaries
      if: ${{ inputs.cache != '' }}
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ./scripts/bins
        key: testbins-${{ hashFiles('scripts/binaries.csv') }}-${{ inputs.cache }}-v2
        enableCrossOsArchive: true

    - name: Run script
      shell: bash
      working-directory: ./scripts
      run: poetry run python ${{ inputs.script }}

    - name: Report results
      if: ${{ inputs.report == 'true' }}
      shell: bash
      working-directory: ./scripts
      run: poetry run python report.py
