coverage:
  status:
    patch:
      target: 50%
      threshold: 10%
    project:
      default:
        threshold: 5%
        target: 80%

ignore:
  - "internal/tui/*.go"
  - "internal/wrapper/*.go"
