name: Setup UI dependencies
description: 'Setup UI dependencies for linting and testing'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        node-version: '22'

    - name: Set up pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        package_json_file: 'ui/package.json'
        version: latest

    - name: Print pnpm version
      shell: bash
      run: pnpm --version

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Upload lockfile
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: pnpm-lock
        path: ui/pnpm-lock.yaml

    - name: Install node dependencies
      shell: bash
      working-directory: ./ui
      run: |
        pnpm install --frozen-lockfile
