name: Build UI

on:
  push:
    branches:
      - $default-branch
    paths: 
      - 'ui/**'
      - '.github/workflows/build-webui.yml'
  pull_request:
    paths:
      - 'ui/**'
      - '.github/workflows/build-webui.yml'
  workflow_call:
    inputs:
      external_call:
        description: 'To distinguish workflow_call from regular push'
        type: boolean
        required: false
        default: true
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  build_webui:
    name: Build Treemap WebUI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          standalone: true
          package_json_file: 'ui/package.json'
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
          cache-dependency-path: './ui/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ./ui
        run: pnpm install

      - name: Build
        working-directory: ./ui
        run: pnpm run build:ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          PULL_REQUEST_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Release
        if: ${{ !inputs.external_call }}
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          artifactContentType: 'text/html'
          artifacts: 'ui/dist/webui/index.html'
          tag: ui-v1
          commit: master
          prerelease: true

      - name: Upload artifact
        if: ${{ inputs.external_call }}
        uses: actions/upload-artifact@v4
        with:
          name: ui
          path: 'ui/dist/webui/index.html'


      