name: Build UI

on:
  workflow_call:
    inputs:
      release:
        description: 'Make a release for the UI'
        type: boolean
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  build-webui:
    name: Build Treemap WebUI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup UI dependencies
        uses: ./.github/actions/setup-ui-deps

      - name: Build
        working-directory: ./ui
        run: pnpm run build:ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          PULL_REQUEST_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Release
        if: ${{ inputs.release }}
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          artifactContentType: 'text/html'
          artifacts: 'ui/dist/webui/index.html'
          tag: ui-v1
          commit: master
          prerelease: true

      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: ui
          path: 'ui/dist/webui/index.html'


      