name: Build UI

on:
  workflow_call:
    inputs:
      release:
        description: 'Make a release for the UI'
        type: boolean
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  build-webui:
    name: Build Treemap WebUI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-ui-deps

      - name: Build
        working-directory: ./ui
        run: pnpm run build:ui
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          PULL_REQUEST_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Release
        if: ${{ inputs.release }}
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          artifactContentType: 'text/html'
          artifacts: 'ui/dist/webui/index.html'
          tag: ui-v1
          commit: master
          prerelease: true

      - name: Upload artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: ui
          path: 'ui/dist/webui/index.html'


      