name: Goreleaser

on:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build-ui:
    name: Build Treemap WebUI
    permissions:
      contents: write
    uses: ./.github/workflows/build-webui.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  goreleaser:
    name: Release
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Get tags
        run: git fetch --tags

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - name: Download UI file
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: ui
          path: internal/webui

      - name: Collect profiles
        uses: ./.github/actions/setup-script
        with:
          cache: 'integration-real'
          script: 'pgo.py'

      - name: Download deps
        run: go mod download

      - name: Build and release
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1.3.2
        with:
          subject-path: 'dist/go-size-analyzer*.*'