name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '36 15 * * 5'

permissions:
  contents: read

jobs:
  eslint:
    permissions:
      security-events: write
      checks: write
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: ./.github/actions/setup-ui-deps

      - name: Run ESLint
        working-directory: ./ui
        run: >-
          pnpm eslint .
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@8214744c546c1e5c8f03dde8fab3a7353211988d # v3.26.7
        with:
          sarif_file: ./ui/eslint-results.sarif
          wait-for-processing: true

  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      checks: write
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.23.1'
          cache: false
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: 'latest'
          install-mode: 'binary'
          args: '--out-format=colored-line-number,sarif:golangci-lint-results.sarif'
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@8214744c546c1e5c8f03dde8fab3a7353211988d # v3.26.7
        with:
          sarif_file: ./golangci-lint-results.sarif
          wait-for-processing: true

  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: typos-action
        uses: crate-ci/typos@945d407a5fc9097f020969446a16f581612ab4df # v1.24.5
        with:
          config: typos.toml
