name: Goreleaser

on:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build-ui:
    name: Build Treemap WebUI
    permissions:
      contents: write
    uses: ./.github/workflows/build-webui.yml
    with:
      release: false

  goreleaser:
    name: Release
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Get tags
        run: git fetch --tags

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.23.0'
          cache: true
          check-latest: true

      - name: Download UI file
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ui
          path: internal/webui

      - name: Collect profiles
        uses: ./.github/actions/setup-script
        with:
          cache: 'integration-real'
          script: 'pgo.py'
          coverage: 'true'

      - name: Download deps
        run: go mod download

      - name: Build and release
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@6149ea5740be74af77f260b9db67e633f6b0a9a1 # v1.4.2
        with:
          subject-path: 'dist/go-size-analyzer*.*'

      - name: Upload build provenance
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          asset_name: attestations.intoto.jsonl
          file: ${{ steps.attest.outputs.bundle-path }}
          overwrite: false