name: Goreleaser

on:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  build-ui:
    name: Build Treemap WebUI
    permissions:
      contents: write
    uses: ./.github/workflows/build-webui.yml
    with:
      release: false

  goreleaser:
    name: Release
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs: build-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get tags
        run: git fetch --tags

      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: '1.23.2'
          cache: true
          check-latest: true

      - name: Download UI file
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ui
          path: internal/webui

      - name: Collect profiles
        uses: ./.github/actions/setup-script
        with:
          cache: 'integration-real'
          script: 'pgo.py'
          coverage: 'true'

      - name: Download deps
        run: go mod download

      - name: Build and release
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        with:
          subject-path: 'dist/go-size-analyzer*.*'

      - name: Upload build provenance
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
        with:
          asset_name: attestations.intoto.jsonl
          file: ${{ steps.attest.outputs.bundle-path }}
          overwrite: false