name: Tests UI

on:
  push:
    branches:
      - master
  pull_request:

permissions: read-all

jobs:
  build-wasm:
    name: Build WASM
    uses: ./.github/workflows/build-wasm.yml

  tests_ui:
    name: Tests on UI
    runs-on: ubuntu-latest
    needs: build-wasm
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '22'

      - name: Set up pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          standalone: true
          package_json_file: 'ui/package.json'
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./ui
        run: pnpm install

      - name: Download WASM
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: wasm
          path: ui/

      - name: Run tests
        working-directory: ./ui
        run: pnpm test

      - name: Upload coverage
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ui
          name: Web UI tests
          directory: ./ui
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@1b5b448b98e58ba90d1a1a1d9fcb72ca2263be46 # v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Web UI tests
          flags: ui
          file: ./ui/test-results.xml
          verbose: true