name: Tests

on:
  push:
    branches:
      - $default-branch
  pull_request:

permissions:
  contents: write
  checks: write
  pull-requests: read

jobs:
  build-ui:
    name: Build Web UI
    uses: ./.github/workflows/build-webui.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  tests:
    name: Tests
    needs: build-ui
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
        test: [ unit, integration-example, integration-real ]
        profile: [ main, other ]
        include:
          - test: unit
            test_type: unit
          - test: integration-example
            test_type: integration
          - test: integration-real
            test_type: integration
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
          check-latest: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          check-latest: true
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'

      - name: Add python dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Download UI file
        uses: actions/download-artifact@v4
        with:
          name: ui

      - name: Move UI file
        run: mv index.html internal/webui/index.html

      - name: Cache test binaries
        uses: actions/cache@v4
        with:
          path: scripts/bins
          key: testbins-${{ hashFiles('scripts/binaries.csv') }}-${{ matrix.test }}
          enableCrossOsArchive: true

      - name: Download deps
        run: go mod download

      - name: Run tests
        run: python scripts/tests.py --${{ matrix.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROFILE: ${{ matrix.profile }}

      - name: Upload coverage
        if: ${{ matrix.profile == 'main' }}
        uses: codecov/codecov-action@v4.4.1
        with:
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ matrix.test_type }}.profile
          flags: ${{ matrix.test_type }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-${{ matrix.test }}-${{ matrix.profile }}-results
          path: results/

  merge:
    name: Merge results
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-13, macos-14 ]
    steps:
      - name: Merge
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ matrix.os }}-results
          compression-level: '9'
          pattern: ${{ matrix.os }}-*-results
          delete-merged: true
          retention-days: 7

